### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by Liquinaut** [TheBoxer/generator-bxrextra#6]
No matter what I try, after the question

`Do you want a Drag and Drop sorting in sample grid?`

I get the following error message:

```
undefined:37
 if (elements.indexOf('Plugins') != -1) { ;
             ^
TypeError: Cannot read property 'indexOf' of undefined
    at eval (eval at template (/var/www/home/phemmen/generator-bxrextra/node_modules/yeoman-generator/node_modules/lodash/dist/lodash.js:5879:22), <anonymous>:37:14)
    at BxrextraGenerator.underscore [as _engine] (/var/www/home/phemmen/generator-bxrextra/node_modules/yeoman-generator/lib/util/engines.js:33:30)
    at BxrextraGenerator.engine (/var/www/home/phemmen/generator-bxrextra/node_modules/yeoman-generator/lib/actions/actions.js:302:10)
    at BxrextraGenerator.template (/var/www/home/phemmen/generator-bxrextra/node_modules/yeoman-generator/lib/actions/actions.js:280:15)
    at BxrextraGenerator.app (/var/www/home/phemmen/generator-bxrextra/app/index.js:197:10)
    at /var/www/home/phemmen/generator-bxrextra/node_modules/yeoman-generator/lib/base.js:316:43
    at /var/www/home/phemmen/generator-bxrextra/node_modules/yeoman-generator/node_modules/async/lib/async.js:551:21
    at /var/www/home/phemmen/generator-bxrextra/node_modules/yeoman-generator/node_modules/async/lib/async.js:227:13
    at iterate (/var/www/home/phemmen/generator-bxrextra/node_modules/yeoman-generator/node_modules/async/lib/async.js:134:13)
    at /var/www/home/phemmen/generator-bxrextra/node_modules/yeoman-generator/node_modules/async/lib/async.js:145:25
```

yo v1.3.3
npm 2.5.1
nodejs v0.12.0

If you need further information, please let me know.
Thnx.

**Comment by TheBoxer** [comment]
Can you please send me all answers you sent?

**Comment by renanbastos93** [comment]
I'm with problem, Someone help-me please.

```
TypeError: success.rows[0].indexOf is not a function
    at SERVICE.listAll.then.success (/mnt/c/Users/renan.bastos/Desktop/git/api-routine-webmonitor/webService/controllers/TrendWeb.js:11:48)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)```js
